disabled_rules:
  - trailing_whitespace
  - line_length
  - identifier_name

opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_init

included:
  - KidLearn

excluded:
  - KidLearnTests
  - KidLearnUITests

reporter: "xcode"

type_body_length:
  warning: 400
  error: 600

file_length:
  warning: 600
  error: 1000

function_body_length:
  warning: 80
  error: 120

nesting:
  type_level: 4

cyclomatic_complexity:
  ignores_case_statements: true